### ISSUE TITLE
Unknown custom metadata item with latest Roslyn release

### ISSUE THREAD

**Issue by kant2002** [jbevain/cecil#211]
When reading the PDB file generated by Roslyn following exception generated

```
Exception: Microsoft.Cci.Pdb.PdbDebugException: Unknown custom metadata item kind: 6
   at Microsoft.Cci.Pdb.PdbFunction.ReadCustomMetadata(BitAccess bits) in c:\Data\Temp\cecil-light\symbols\pdb\Microsoft.Cci.Pdb\PdbFunction.cs:line 327
   at Microsoft.Cci.Pdb.PdbFunction..ctor(String module, ManProcSym proc, BitAccess bits) in c:\Data\Temp\cecil-light\symbols\pdb\Microsoft.Cci.Pdb\PdbFunction.cs:line 251
   at Microsoft.Cci.Pdb.PdbFunction.LoadManagedFunctions(String module, BitAccess bits, UInt32 limit, Boolean readStrings) in c:\Data\Temp\cecil-light\symbols\pdb\Microsoft.Cci.Pdb\PdbFunction.cs:line 125
   at Microsoft.Cci.Pdb.PdbFile.LoadFuncsFromDbiModule(BitAccess bits, DbiModuleInfo info, IntHashTable names, ArrayList funcList, Boolean readStrings, MsfDirectory dir, Dictionary`2 nameIndex, PdbReader reader) in c:\Data\Temp\cecil-light\symbols\pdb\Microsoft.Cci.Pdb\PdbFile.cs:line 298
   at Microsoft.Cci.Pdb.PdbFile.LoadFunctions(Stream read, BitAccess bits, Boolean readAllStrings, Int32& age, Guid& guid) in c:\Data\Temp\cecil-light\symbols\pdb\Microsoft.Cci.Pdb\PdbFile.cs:line 396
   at Mono.Cecil.Pdb.PdbReader.PopulateFunctions() in c:\Data\Temp\cecil-light\symbols\pdb\Mono.Cecil.Pdb\PdbReader.cs:line 91
   at Mono.Cecil.Pdb.PdbReader.ProcessDebugHeader(ImageDebugDirectory directory, Byte[] header) in c:\Data\Temp\cecil-light\symbols\pdb\Mono.Cecil.Pdb\PdbReader.cs:line 75
   at Mono.Cecil.ModuleDefinition.ProcessDebugHeader() in c:\Data\Temp\cecil-light\Mono.Cecil\ModuleDefinition.cs:line 763
   at Mono.Cecil.ModuleDefinition.ReadSymbols(ISymbolReader reader) in c:\Data\Temp\cecil-light\Mono.Cecil\ModuleDefinition.cs:line 824
   at Mono.Cecil.ModuleReader.ReadSymbols(ModuleDefinition module, ReaderParameters parameters) in c:\Data\Temp\cecil-light\Mono.Cecil\AssemblyReader.cs:line 105
   at Mono.Cecil.ModuleReader.CreateModuleFrom(Image image, ReaderParameters parameters) in c:\Data\Temp\cecil-light\Mono.Cecil\AssemblyReader.cs:line 83
   at Mono.Cecil.ModuleDefinition.ReadModule(Stream stream, ReaderParameters parameters) in c:\Data\Temp\cecil-light\Mono.Cecil\ModuleDefinition.cs:line 855
   at Mono.Cecil.ModuleDefinition.ReadModule(String fileName, ReaderParameters parameters) in c:\Data\Temp\cecil-light\Mono.Cecil\ModuleDefinition.cs:line 839
   at Cosmos.IL2CPU.AppAssembler.GetCecilMethodDefinitionForSymbolReading(MethodBase methodBase) in c:\Users\<user>\Documents\GitHub\Cosmos-1\source\Cosmos.IL2CPU\AppAssembler.cs:line 1575
   at Cosmos.IL2CPU.AppAssembler.MethodBegin(MethodInfo aMethod) in c:\Users\<user>\Documents\GitHub\Cosmos-1\source\Cosmos.IL2CPU\AppAssembler.cs:line 226
   at Cosmos.IL2CPU.AppAssembler.ProcessMethod(MethodInfo aMethod, List`1 aOpCodes) in c:\Users\kant\Documents\GitHub\Cosmos-1\source\Cosmos.IL2CPU\AppAssembler.cs:line 462
   at Cosmos.IL2CPU.ILScanner.Assemble() in c:\Users\<user>\Documents\GitHub\Cosmos-1\source\Cosmos.IL2CPU\ILScanner.cs:line 929
   at Cosmos.IL2CPU.ILScanner.Execute(MethodBase aStartMethod) in c:\Users\kant\Documents\GitHub\Cosmos-1\source\Cosmos.IL2CPU\ILScanner.cs:line 251
   at Cosmos.IL2CPU.CompilerEngine.Execute() in c:\Users\<user>\Documents\GitHub\Cosmos-1\source\Cosmos.IL2CPU\CompilerEngine.cs:line 238
```

**Comment by SimonCropp** [comment]
what version of cecil?

can you upload the offending binary and pdb somewhere?

**Comment by kant2002** [comment]
Version 0.9.4 and 0.9.5 both produce same results. I working on create minimum viable library for testing.

**Comment by SimonCropp** [comment]
the current released version is 0.9.6.1 can you try that http://www.nuget.org/packages/Mono.Cecil/0.9.6.1

**Comment by kant2002** [comment]
I just update to 0.9.6.1 and this was fixed. Thanks.

**Comment by SimonCropp** [comment]
no worries :)
