### ISSUE TITLE
NullReferenceException in GetNestedType

### ISSUE THREAD

**Issue by rouen-sk** [jbevain/cecil#233]
In Xamarin Android applications, Mono.Cecil is used for linking. If the assemblies are obfuscated with CryptoObfuscator for .NET first, I get this error in build:

The "LinkAssemblies" task failed unexpectedly.
System.NullReferenceException: Object reference not set to an instance of an
object.
   at Mono.Cecil.Mixin.GetNestedType(TypeDefinition self, String name)
   at Mono.Cecil.TypeParser.TryGetDefinition(ModuleDefinition module, Type
type_info, TypeReference& type)
   at Mono.Cecil.TypeParser.GetTypeReference(ModuleDefinition module, Type
type_info)
   at Mono.Cecil.TypeParser.ParseType(ModuleDefinition module, String fullname)
   at Mono.Cecil.SignatureReader.ReadTypeReference()
   at Mono.Cecil.SignatureReader.ReadCustomAttributeElementValue(TypeReference
type)
   at Mono.Cecil.SignatureReader.ReadCustomAttributeElement(TypeReference type)
   at Mono.Cecil.SignatureReader.ReadCustomAttributeFixedArgument(TypeReference
type)
   at
Mono.Cecil.SignatureReader.ReadCustomAttributeConstructorArguments(CustomAttribute
attribute, Collection`1 parameters)
   at Mono.Cecil.MetadataReader.ReadCustomAttributeSignature(CustomAttribute
attribute)
   at Mono.Cecil.CustomAttribute.<Resolve>m__1(CustomAttribute attribute,
MetadataReader reader)
   at Mono.Cecil.ModuleDefinition.Read[TItem,TRet](TItem item, Func`3 read)
   at Mono.Cecil.CustomAttribute.Resolve()
   at Mono.Cecil.CustomAttribute.get_HasConstructorArguments()
   at Mono.Linker.Steps.MarkStep.MarkCustomAttributeArguments(CustomAttribute
ca)
   at Mono.Linker.Steps.MarkStep.MarkCustomAttribute(CustomAttribute ca)
   at Mono.Linker.Steps.MarkStep.MarkCustomAttributes(ICustomAttributeProvider
provider)
   at Mono.Linker.Steps.MarkStep.ProcessMethod(MethodDefinition method)
   at Mono.Linker.Steps.MarkStep.ProcessQueue()
   at Mono.Linker.Steps.MarkStep.Process()
   at Mono.Linker.Steps.MarkStep.Process(LinkContext context)
   at Mono.Linker.Pipeline.Process(LinkContext context)
   at MonoDroid.Tuner.Linker.Process(LinkerOptions options, LinkContext&
context)
   at Xamarin.Android.Tasks.LinkAssemblies.Execute()
   at
Microsoft.Build.BackEnd.TaskExecutionHost.Microsoft.Build.BackEnd.ITaskExecutionHost.Execute()
   at
Microsoft.Build.BackEnd.TaskBuilder.<ExecuteInstantiatedTask>d__20.MoveNext()

So I get sources, found GetNestedType in Mono.Cecil.Mixin and after replacing line 

if (!self.HasNestedTypes)
 return null;

wtih 

if (self == null || !self.HasNestedTypes)
                return null;

the error disappear and linking is successful. It is quite strange, because in `TryGetDefinition (ModuleDefinition module, Type type_info, out TypeReference type)` there is check for null before calling `typedef.GetNestedType (nested_names [i])`. 

Any ideas, how this error can even occur? And would be maybe possible to include the null check into GetNestedType (as I tried it) into Cecil source code, to prevent these errors, so me (and other Xamarin users i guess) would not have to hack&replace Xamarin.Android.Cecil.dll ? Thanks!

**Comment by jbevain** [comment]
I don't maintain Xamarin.Android, so I can't help with that part. I can however fix the NRE :)

Is there any chance you could upload the obfuscated binary?

**Comment by jbevain** [comment]
Fixed in 3723f62e1a68e27338490483dea387c02110049f. Thanks!
