### ISSUE TITLE
Round-trip should be possible without resolving any references

### ISSUE THREAD

**Issue by poizan42** [jbevain/cecil#236]
There's no reason that simply reading a module and writing back a module should need to resolve anything, yet it does. It's frustrating and pointless that you need to be able to locate referenced assemblies just to make a change as small as flipping a bit (literally what I were doing when I hit this problem; setting IsWindowsRuntime true on a reference).

I don't really have a good overview on the exact places where this issue crops up, both the first place I hit it was because of a custom attribute - SignatureReader.ReadCustomAttributeEnum wants the underlying type of the enum.

**Comment by jbevain** [comment]
Hi Kasper,

>> Round-trip should be possible without resolving any references

You wouldn't believe how much I'd like this to be true and how much I tried to make it so. But it's not the case. You can grep the source for the usage of CheckedResolve, there's exactly two cases where Cecil needs to resolve a TypeRef to write it properly:

* When you have a const field with a TypeRef to an enum.
* When you have a custom attribute instantiated with a TypeRef to an enum.

There's no way to know the underlying time (and thus the size it takes when serialized) of an enum from a TypeRef. Cecil needs to resolve them to know how much to read and how much to write.

**Comment by poizan42** [comment]
Why do we need the size of each parameter if we are just copying all of them? We do know the length of the CustomAttrib blob, so we can just copy that as-is even if we don't know what exactly it means.

**Comment by jbevain** [comment]
If you don't access the custom attribute values, it should be copied as is, using its byte[] blob. If you do, we'll need the size to properly write it back.

We're not doing that for constants. It could be done though, but you say you're seeing the resolve request from ReadCustomAttributeEnum.

**Comment by poizan42** [comment]
Apparently it isn't, not always at least.

Steps to reproduce:
* Create a F# class library project named "AttrFS".
* Add the "FSharp.Core for F# 4.0" nuget package version 4.0.0.1 to the F# project. (More specifically make sure you are using a version of FSharp.Core that isn't in the GAC).
* Add the following file to the F# project:
```F#
namespace cecil_236.AttrFS

type TestClass() = 
    member TestClass.Fun1 = ()
```
* Create a C# project referencing Mono.Cecil with the following code:
```C#
using Mono.Cecil;

namespace cecil_236
{
  class Program
  {
    static void Main(string[] args)
    {
      var mod = ModuleDefinition.ReadModule("AttrFS.dll");
      mod.Write("AttrFS1.dll");
    }
  }
}
```
* Build the C# project.
* Copy the AttrFS.dll to somewhere without the FSharp.Core.dll file (or delete the FSharp.Core.dll file from the output directory).
* Now run the C# program in the directory with the AttrFS.dll file.

What happens is that we get the following exception:
```
Mono.Cecil.AssemblyResolutionException was unhandled
  HResult=-2147024894
  Message=Failed to resolve assembly: 'FSharp.Core, Version=4.4.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'
  Source=Mono.Cecil
  StackTrace:
       at Mono.Cecil.BaseAssemblyResolver.Resolve(AssemblyNameReference name, ReaderParameters parameters)
       at Mono.Cecil.BaseAssemblyResolver.Resolve(AssemblyNameReference name)
       at Mono.Cecil.DefaultAssemblyResolver.Resolve(AssemblyNameReference name)
       at Mono.Cecil.MetadataResolver.Resolve(TypeReference type)
       at Mono.Cecil.ModuleDefinition.Resolve(TypeReference type)
       at Mono.Cecil.TypeReference.Resolve()
       at Mono.Cecil.Mixin.CheckedResolve(TypeReference self)
       at Mono.Cecil.SignatureReader.ReadCustomAttributeEnum(TypeReference enum_type)
       at Mono.Cecil.SignatureReader.ReadCustomAttributeElementValue(TypeReference type)
       at Mono.Cecil.SignatureReader.ReadCustomAttributeElement(TypeReference type)
       at Mono.Cecil.SignatureReader.ReadCustomAttributeFixedArgument(TypeReference type)
       at Mono.Cecil.SignatureReader.ReadCustomAttributeConstructorArguments(CustomAttribute attribute, Collection`1 parameters)
       at Mono.Cecil.MetadataReader.ReadCustomAttributeSignature(CustomAttribute attribute)
       at Mono.Cecil.CustomAttribute.<Resolve>b__2(CustomAttribute attribute, MetadataReader reader)
       at Mono.Cecil.ModuleDefinition.Read[TItem,TRet](TItem item, Func`3 read)
       at Mono.Cecil.CustomAttribute.Resolve()
       at Mono.Cecil.CustomAttribute.get_ConstructorArguments()
       at Mono.Cecil.ImmediateModuleReader.ReadCustomAttributes(ICustomAttributeProvider provider)
       at Mono.Cecil.ImmediateModuleReader.ReadType(TypeDefinition type)
       at Mono.Cecil.ImmediateModuleReader.ReadTypes(Collection`1 types)
       at Mono.Cecil.ImmediateModuleReader.ReadModule(ModuleDefinition module)
       at Mono.Cecil.ModuleWriter.WriteModuleTo(ModuleDefinition module, Stream stream, WriterParameters parameters)
       at Mono.Cecil.ModuleDefinition.Write(Stream stream, WriterParameters parameters)
       at Mono.Cecil.ModuleDefinition.Write(String fileName, WriterParameters parameters)
       at Mono.Cecil.ModuleDefinition.Write(String fileName)
       at cecil_236.Program.Main(String[] args) in c:\Users\kb\Documents\Visual Studio 2012\Projects\cecil-236\cecil-236\Program.cs:line 10
       at System.AppDomain._nExecuteAssembly(RuntimeAssembly assembly, String[] args)
       at System.AppDomain.ExecuteAssembly(String assemblyFile, Evidence assemblySecurity, String[] args)
       at Microsoft.VisualStudio.HostingProcess.HostProc.RunUsersAssembly()
       at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
       at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
       at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
       at System.Threading.ThreadHelper.ThreadStart()
  InnerException: 
```

**Comment by jbevain** [comment]
Nice! Any chance you could upload a pre-built AttrFS.dll for me somewhere?

**Comment by poizan42** [comment]
lzma compressed and base64 encoded:
```
/Td6WFoAAAFpIt42AgAhAQEAAABSQCtu4BH/BWddACaWjnAAF/fsBbvq9P+UAS9E73zm9QkZRAIp
/1PN1tEU/p5hnIIV9gl6rGu07VQQnibKcc/FRyvI6yJF/kH6s1mPcgQJgG86bF7FVAXcqCcRClyf
j1G5vGXwJF+PY3VikS1b+zwvI+JMasU/KJcnWQSkBktb3cWI2C4RuhsAFduPUY20bu9OFjsPVOn+
1SEv03J9guTrNj6VL2xBrjLuvYbhPk9AfomYOokOObGwN82rkcmJDEUPmBz6/IirrJCpzEqsSVwr
urj4pwnsRz/7YAY7iPoGai8CgA76H68DCbP9NVRYUTVPQ0sLBizlqFV4MDswVbEThUJTt3iiFw6K
GfXsy3OiH/3u4qW5Cs6DsNueLKNCZYNEKLoD73YZgbFVLHbyLLV/UChT+xionIr7MaNGQhv1WDJi
NqpFKMel4VyTER2yNU/Q8VElVDG8vdM79ftXUy78T6WD9XYOjuYDmydC8A8zD+7Lz+1vSCeiSe1v
VKWXwPeyZE1BkAaD4uGsE2zD1kd6u/CH4/x7ZsSpfb5pZN4C7JF2uVM4/lZyOYmVVRJK2iHprc3x
FnOTj08/KwUsPhwfifA5vA718S5eMCF2BjezohBI1ehoexsxztDEP3Cli62hPJWKkCOsdn9er/me
6a9QYvwgZ7cS2L1AloewwctL65o4J77fHQuG5UJmEsuaet3fQXnB99MspL+aIrDpJUD+GXBVpaMD
OFJFQ9XrSAfn239nETy+QT4wexGSqaqdSJzcIwP9RbHLMQgBFrUo7bb547EPEZh1UWBUu8fR6GTD
DedJzsOnD/5IanUm/bqEQpPd93HuIPsArnCW68WTVxQ/75GswjzGsLoIKFhcH3EPMJn4GnSCJrqm
AWXF4UtgaCiGeRy98d5lbb92OnUmMnf4Ud7M1PvZxaJcoXnycGNPX1xm1jA6A9JumIGF8Vf/Myyr
2yQK3OajEpUsJsBfJpTTgCO14ILifQ5ZWLxpZooLxJzJX2RAB85B7lQ/keP49IBeXcVxf0qZuj9U
BcS/CaAcgbNLuRMQ97Ea3fLNY0i5+IE0xVSzhxI9SYx9EDHV+B5TtZGx6LMw5+MccLGajH/47Q9N
h+3dBaFHm9vTCQaZOh/maSN//ggZWGwN7VONP5uQnq5+q1NCR0fwePd+jzlrxIc3j7vJHfCPfkN+
GG9pGho28zXvOpDPU2UYUOVw0TZd1K5+YnsGXt/VzmlstV9A80pCrL8BOjurCr3bsLaIKXrbAE7B
EHXxnNy6zDvgEZ/oBKqiUVirwtLGvfOdQ+BEv8pTmadKLdjcoT0GPOBzLmz38dhBJ8L6yosAtSzE
0UaKknwOPl28EDOO1pdip1MNRnOsgRwRB5Pqbw/mNcAuiG8nqze4ZlLcf0TzAh9jAh4UvxNFL/wB
kDabpRyBSfKvaro4LeXqrNe1/eMwFmgcPdq4K7qFoaM6wnz0p24GeDdKofzO0biRmsHkvTVJi6d4
PGVr1NBmduJzqYUADn+Wes0rvqV6ucOJpu4Lc3PH0u6drBf6ztPF7/+6+oryOQOARTZME3NF/Lmt
aLpJTYERRE7RG9QvGcIkbun0FlZ60S0b4Hj3q7qP0IdSeohcU3I29c2rLddRFOazw39oYFPnMj8e
k8UMesGWAjdLmCVLz/OTSIrBomM5g7R0qbx6drTnl3JH95WamGEjkwC8Ox2aCPxTekdNXe3JYffj
g/gR+sl316Y76q9Uhtu6a6FlznQzYH97TrnrUs1RpqCcpFcS8OrMSCy+59xqsZjhyJZ69FOQOEmp
l5t8JdOaP7lurWtTAVVfIyCXaTyQ6UIJQFTVFfL+RE9G5OTDda6p4EnJW7n1AAAASllfAAAB/wqA
JAAAtz88vz4wDYsCAAAAAAFZWg==
```

**Comment by jbevain** [comment]
Cool, and good catch.

From what I can tell that's a regression introduced by b84a79789c0ec30e1c74a24ed8640a547fb38c19.

It used to be the case that the ImmediateModuleReader would not resolve CustomAttribute, as we support writing them back unresolved.

But then in the ModuleWriter we're using the ImmediateModuleReader to read the assembly into its object model before writing it back.

The fix is to honor both cases. Make sure that when the module is first read as immediate we read the custom attributes, but not when we're about to write the module.

**Comment by jbevain** [comment]
That should be fixed in master.

I'll see about using the same pattern for constants. That should prevent any resolution if you don't access the custom attributes or the constants.

**Comment by jbevain** [comment]
@poizan42 do you confirm the fix?

**Comment by poizan42** [comment]
Yup, LGTM
