### ISSUE TITLE
Cecil error on ImportGenericParameter

### ISSUE THREAD

**Issue by eiriktsarpalis** [jbevain/cecil#278]
I came across this rare issue when passing a piece of code to the [AssemblySaver](https://github.com/jbevain/mono.reflection/tree/assembly-saver) implementation:
```csharp
public class A<T> { }
public class B<T, U> { }
public class C
{
    public static A<U> G<T, U>(T x) { return null; }
    public static A<U> F<T, U>(T x) { return C.G<Func<T>, U>(() => x); }
}
public class D
{
    public static A<U> F<T, S, U>(A<B<T, S>> x) { return C.F<A<B<T, S>>, U>(x); }
}
```
when passed to
```csharp
AssemblySaver.SaveTo(typeof(D).Assembly, "foo.dll")
```
Results in the following error:
```
System.ArgumentOutOfRangeException: Specified argument was out of the range of valid values.
   at Mono.Collections.Generic.Collection`1.get_Item(Int32 index)
   at Mono.Cecil.ImportGenericContext.MethodParameter(String method, Int32 position)
   at Mono.Cecil.ReflectionImporter.ImportGenericParameter(Type type, ImportGenericContext context)
   at Mono.Cecil.ReflectionImporter.ImportTypeSpecification(Type type, ImportGenericContext context)
   at Mono.Cecil.ReflectionImporter.ImportType(Type type, ImportGenericContext context, ImportGenericKind import_kind)
   at Mono.Cecil.ReflectionImporter.ImportType(Type type, ImportGenericContext context)
   at Mono.Cecil.ReflectionImporter.ImportMethodSpecification(MethodBase method, ImportGenericContext context)
   at Mono.Cecil.ReflectionImporter.ImportMethod(MethodBase method, ImportGenericContext context, ImportGenericKind import_kind)
   at Mono.Cecil.ReflectionImporter.ImportReference(MethodBase method, IGenericParameterProvider context)
   at Mono.Cecil.ModuleDefinition.ImportReference(MethodBase method, IGenericParameterProvider context)
   at Mono.Cecil.ModuleDefinition.Import(MethodBase method, IGenericParameterProvider context)
   at Mono.Reflection.MetadataMapper.CreateReference(MethodBase method, MethodReference context)
   at Mono.Reflection.MetadataMapper.MapInstructions(MethodBase method, MethodDefinition method_definition)
   at Mono.Reflection.MetadataMapper.MapMethodBody(MethodBase method, MethodDefinition method_definition)
   at Mono.Reflection.MetadataMapper.MapMethod(TypeDefinition type_definition, MethodBase method)
   at Mono.Reflection.MetadataMapper.MapType(Type type, TypeDefinition declaringType)
   at Mono.Reflection.MetadataMapper.Map()
   at Mono.Reflection.MetadataMapper.MapAssembly(Assembly assembly)
   at Mono.Reflection.AssemblySaver.SaveTo(Assembly assembly, Stream stream)
   at Mono.Reflection.AssemblySaver.SaveTo(Assembly assembly, String fileName)
```
The issue seems to be caused by the fact that methods `C.F` and `D.F` share the same name. This results in [this method](https://github.com/jbevain/cecil/blob/042bdd2432705ae4c682743ff9740550dee3bead/Mono.Cecil/Import.cs#L75) selecting an incorrect candidate from the stack.

Related to https://github.com/mbraceproject/MBrace.Core/issues/169

**Comment by jbevain** [comment]
That does not look fun at all :)

**Comment by isaacabraham** [comment]
Thanks for the quick fix on this! Any idea when this will be pushed to nuget?
