### ISSUE TITLE
NullReferenceException during writing assembly when it contains async method of renamed type

### ISSUE THREAD

**Issue by Serg046** [jbevain/cecil#295]
Just run this code

```
public class NonNestedAsyncClass
{
    public async Task AsyncMethod()
    {
        await Task.Delay(1);
    }
}

public class ParentClass
{
    public class NestedSyncClass
    {
        public void SomeMethod()
        {
            Debug.WriteLine("test");
        }
    }

    public class NestedAsyncClass
    {
        public async Task AsyncMethod()
        {
            await Task.Delay(1);
        }
    }
}

class Program
{
    static void Main(string[] args)
    {
        WriteType(typeof(NonNestedAsyncClass)); //success
        WriteType(typeof(ParentClass.NestedSyncClass)); //success
        WriteType(typeof(ParentClass.NestedAsyncClass), false); //success
        WriteType(typeof(ParentClass.NestedAsyncClass)); //NullReferenceException
    }

    private static void WriteType(Type sourceType, bool needToRename = true)
    {
        var assemblyDefinition = AssemblyDefinition.ReadAssembly(sourceType.Module.FullyQualifiedName);

        using (var stream = new MemoryStream())
        {
            var type = assemblyDefinition.MainModule.GetType(sourceType.FullName, true);
            if (needToRename)
                type.Name += "CustomName";

            assemblyDefinition.Write(stream);
        }
    }
}
```

The line `Method(typeof(ParentClass.NestedAsyncClass));` throws `System.NullReferenceException`

   at Mono.Cecil.Mixin.GetNestedType(TypeDefinition self, String fullname)
   at Mono.Cecil.TypeParser.TryGetDefinition(ModuleDefinition module, Type type_info, TypeReference& type)
   at Mono.Cecil.TypeParser.GetTypeReference(ModuleDefinition module, Type type_info)
   at Mono.Cecil.TypeParser.ParseType(ModuleDefinition module, String fullname)
   at Mono.Cecil.SignatureReader.ReadCustomAttributeElementValue(TypeReference type)
   at Mono.Cecil.SignatureReader.ReadCustomAttributeElement(TypeReference type)
   at Mono.Cecil.SignatureReader.ReadCustomAttributeFixedArgument(TypeReference type)
   at Mono.Cecil.SignatureReader.ReadCustomAttributeConstructorArguments(CustomAttribute attribute, Collection`1 parameters)
   at Mono.Cecil.MetadataReader.ReadCustomAttributeSignature(CustomAttribute attribute)
   at Mono.Cecil.CustomAttribute.<Resolve>b__34_0(CustomAttribute attribute, MetadataReader reader)
   at Mono.Cecil.ModuleDefinition.Read[TItem,TRet](TItem item, Func`3 read)
   at Mono.Cecil.CustomAttribute.Resolve()
   at Mono.Cecil.CustomAttribute.get_ConstructorArguments()
   at Mono.Cecil.ImmediateModuleReader.ReadCustomAttributes(ICustomAttributeProvider provider)
   at Mono.Cecil.ImmediateModuleReader.ReadMethods(TypeDefinition type)
   at Mono.Cecil.ImmediateModuleReader.ReadType(TypeDefinition type)
   at Mono.Cecil.ImmediateModuleReader.ReadTypes(Collection`1 types)
   at Mono.Cecil.ImmediateModuleReader.ReadType(TypeDefinition type)
   at Mono.Cecil.ImmediateModuleReader.ReadTypes(Collection`1 types)
   at Mono.Cecil.ImmediateModuleReader.ReadModule(ModuleDefinition module)
   at Mono.Cecil.ModuleWriter.WriteModuleTo(ModuleDefinition module, Stream stream, WriterParameters parameters)
   at Mono.Cecil.ModuleDefinition.Write(Stream stream, WriterParameters parameters)
   at Mono.Cecil.AssemblyDefinition.Write(Stream stream)
   at MonoCecil.Program.Method(Type sourceType, Boolean needToRename) in D:\Tests\MonoCecil\MonoCecil\Program.cs:line 56
   at MonoCecil.Program.Main(String[] args) in D:\Tests\MonoCecil\MonoCecil\Program.cs:line 43
   at System.AppDomain._nExecuteAssembly(RuntimeAssembly assembly, String[] args)
   at System.AppDomain.ExecuteAssembly(String assemblyFile, Evidence assemblySecurity, String[] args)
   at Microsoft.VisualStudio.HostingProcess.HostProc.RunUsersAssembly()
   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()

**Comment by jbevain** [comment]
Good catch, thanks for the repro. I think you can workaround it by loading the assembly entirely,

Replace

```csharp
AssemblyDefinition.ReadAssembly(sourceType.Module.FullyQualifiedName);
```

by:

```csharp
AssemblyDefinition.ReadAssembly(sourceType.Module.FullyQualifiedName, new ReaderParameters (ReadingMode.Immediate));
```

**Comment by Serg046** [comment]
Thanks a lot. It works fine.

**Comment by Serg046** [comment]
I downloaded the latest code and cannot reproduce the issue. Looks like it is already fixed. So waiting for a new nuget release :)

**Comment by jbevain** [comment]
You can use the 0.10-beta nuget.

**Comment by Serg046** [comment]
Checked `0.10`, it works fine, thanks.
