### ISSUE TITLE
Make the "stream must be readable and seekable" requirement clearer?

### ISSUE THREAD

**Issue by jskeet** [jbevain/cecil#375]
When trying to read a module with a zip-based stream, I ran into an exception:

```text
Unhandled Exception: System.ArgumentException: Value does not fall within the expected range.
   at Mono.Cecil.Mixin.CheckReadSeek(Stream stream)
   at Mono.Cecil.ModuleDefinition.ReadModule(Stream stream, ReaderParameters parameters)
   at CecilBug.Program.Main(String[] args) in c:\Users\skeet\Test\CecilBug\Program.cs:line 34
```

I was able to fix this easily by copying it into a `MemoryStream` and then passing that in - but it wasn't clear to me that I needed to do so, based on the error message. An error of "Stream must be readable and seekable" (identifying the parameter name of `stream`) would have been more useful, IMO.

**Comment by jbevain** [comment]
Another case of #154 :)
