### ISSUE TITLE
Error when decompiling .NET Standard 2.0 libraries

### ISSUE THREAD

**Issue by terrajobst** [jbevain/cecil#411]
Just tried to decompile a .NET Standard 2.0 binary using ILSpy. It crashes with this exception from Cecil:

```
System.OutOfMemoryException: Array dimensions exceeded supported range.
   at Microsoft.Cci.Pdb.MsfDirectory..ctor(PdbReader reader, PdbFileHeader head, BitAccess bits)
   at Microsoft.Cci.Pdb.PdbFile.LoadFunctions(Stream read, Dictionary`2& tokenToSourceMapping, String& sourceServerData, Int32& age, Guid& guid)
   at Mono.Cecil.Pdb.PdbReader.PopulateFunctions()
   at Mono.Cecil.Pdb.PdbReader.ProcessDebugHeader(ImageDebugDirectory directory, Byte[] header)
   at Mono.Cecil.ModuleDefinition.ProcessDebugHeader()
   at ICSharpCode.ILSpy.LoadedAssembly.LoadSymbols(ModuleDefinition module)
   at ICSharpCode.ILSpy.LoadedAssembly.LoadAssembly(Object state)
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
```

This happens for .NET Standard 2.0 class libraries that are produced from File | New Project in VS. It could be related to the fact that they use the new portable PDB format.

**Comment by jbevain** [comment]
ILSpy should update to Cecil 0.10 to handle portable pdbs, please report the issue there.
