### ISSUE TITLE
Error reading PDB of VB.Net assemblies when namespace starts with 'A'

### ISSUE THREAD

**Issue by jasonwoods-7** [jbevain/cecil#448]
When calling the get Body property on a MethodDefinition of some VB.Net methods when the assembly's namespace starts with an 'A', the following exception is thrown:

```
System.ArgumentOutOfRangeException : Length cannot be less than zero.
Parameter name: length
   at System.String.Substring(Int32 startIndex, Int32 length)
   at Mono.Cecil.Pdb.NativePdbReader.GetImport(PdbScope scope, ModuleDefinition module)
   at Mono.Cecil.Pdb.NativePdbReader.ReadScopeAndLocals(PdbScope scope, MethodDebugInformation info)
   at Mono.Cecil.Pdb.NativePdbReader.Read(MethodDefinition method)
   at Mono.Cecil.Cil.CodeReader.ReadMethodBody()
   at Mono.Cecil.Cil.CodeReader.ReadMethodBody(MethodDefinition method)
   at Mono.Cecil.MethodDefinition.<>c.<get_Body>b__41_0(MethodDefinition method, MetadataReader reader)
   at Mono.Cecil.ModuleDefinition.Read[TItem,TRet](TRet& variable, TItem item, Func`3 read)
   at Mono.Cecil.MethodDefinition.get_Body()
```

It looks like this error was introduced in Mono.Cecil v. 0.10.0-beta5.

I took a look at the PDB files generated by the VB compiler and they don't seem to do things the same way as C# does.  They seem to use an `@P:` instead of a `U` to signify importing of a namespace.

I added a [repo](https://github.com/jasonwoods-7/AVbTest) to show the issue.

**Comment by jbevain** [comment]
Ahah, good catch. Thanks for the repro, I'll have a look.

**Comment by jbevain** [comment]
Should be fixed in master. Thanks!
