### ISSUE TITLE
File is being used by another process

### ISSUE THREAD

**Issue by wsrf16** [jbevain/cecil#451]
Version : 0.10.0-beta6
----------------------------------------------------------------------------------------------------------
string assemblyFile = "xxx.dll";
AssemblyDefinition Assembly = AssemblyDefinition.ReadAssembly(assemblyFile, readParams);
Assembly.Write(assemblyFile);
----------------------------------------------------------------------------------------------------------
StackTrace:
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share)
   at Mono.Cecil.ModuleDefinition.Write(String fileName, WriterParameters parameters)
   at Mono.Cecil.AssemblyDefinition.Write(String fileName, WriterParameters parameters)
----------------------------------------------------------------------------------------------------------
I write to the same file after I read xxx.dll. It tell me "The process cannot access the file because it is being used by another process".
But it is passed in version 0.96.

**Comment by jbevain** [comment]
Yes, please go through the breaking changes of 0.10 and their suggested fix:

http://cecil.pe/

**Comment by wsrf16** [comment]
Another question:
In version 0.10.0-beta6,I write AssemblyDefinition to new .dll file.But its size become smaller.

**Comment by jbevain** [comment]
What's the question? :)

**Comment by wsrf16** [comment]
I just injected a .cctor into the .dll file.Shouldn't it be bigger?At least it became bigger in 0.96.

**Comment by jbevain** [comment]
Sometimes Cecil will serialize a dll in a more optimal fashion than the original compiler, sometimes not :)

**Comment by wsrf16** [comment]
So it means I can use the smaller .dll safely?
Thx.

**Comment by jbevain** [comment]
You should always use `peverify` to verify that your modified binaries are at least correct, but yes.
