### ISSUE TITLE
IndexOutOfBoundExeption on .Net Core

### ISSUE THREAD

**Issue by richardwerkman** [jbevain/cecil#497]
When calling ReadSymbols an IndexOutOfBoundExeption occurs using .Net Core 2.0. Is this an compatibility issue with .Net Core?

            var readerParameters = new ReaderParameters { AssemblyResolver = assemblyResolver };
            var writerParameters = new WriterParameters();
            var pdbName = Path.ChangeExtension(AssemblyPath, "pdb");

            ISymbolReaderProvider provider = null;

            if (File.Exists(pdbName))
            {
                provider = new PdbReaderProvider();
            }
            var myAssembly = AssemblyDefinition.ReadAssembly(AssemblyPath);
            var module = myAssembly.MainModule;

            var reader = provider.GetSymbolReader(module, pdbName);
            module.ReadSymbols(reader);

Stacktrace:
`   at Microsoft.Cci.Pdb.BitAccess.ReadInt32(Int32& value)
   at Microsoft.Cci.Pdb.BitAccess.ReadInt32(Int32[] values)
   at Microsoft.Cci.Pdb.MsfDirectory..ctor(PdbReader reader, PdbFileHeader head, BitAccess bits)
   at Microsoft.Cci.Pdb.PdbFile.LoadFunctions(Stream read, Dictionary& tokenToSourceMapping, 
   String& sourceServerData, Int32& age, Guid& guid)
   at Mono.Cecil.Pdb.PdbReader.PopulateFunctions()
   at Mono.Cecil.Pdb.PdbReader.ProcessDebugHeader(ImageDebugDirectory directory, Byte[] header)
   at Mono.Cecil.ModuleDefinition.ProcessDebugHeader()
   at CecilExample.PdbCecil.ReadAssembly() in C:\TFS\CecilExample\CecilExample\PdbCecil.cs:line 36
   at CecilExample.Program.Main(String[] args) in C:\TFS\CecilExample\CecilExample\Program.cs:line 14`

**Comment by jbevain** [comment]
Hello,

Which version of Cecil are you using? You need to be using the 0.10 nuget or master to be able to handle the new portable pdb format in .NET Core.

**Comment by richardwerkman** [comment]
Hey,

I was using version 0.9.6.4, now trying to update to 0.10. Some things have changed I see, could you please explain why the sequence points are no longer part of the instructions? My goal is to mutate the IL and show users where the mutation took place. How can I find the matching sequencepoint for a instruction?

Thanks in advance

**Comment by jbevain** [comment]
I wrote about the breaking changes in http://cecil.pe/

Basically, `method.DebugInformation` will have the sequence points.

**Comment by richardwerkman** [comment]
Thanks for pushing me in the right direction. You saved my day! Closing the issue now.
