### ISSUE TITLE
ArgumentNullException in InstructionOffset constructor

### ISSUE THREAD

**Issue by mfkl** [jbevain/cecil#506]
Hi there,

```
Value cannot be null.
Parameter name: instruction
System.ArgumentNullException: Value cannot be null.
Parameter name: instruction
   at Mono.Cecil.Cil.InstructionOffset..ctor(Instruction instruction)
   at Mono.Cecil.Cil.CodeReader.ReadScope(ScopeDebugInformation scope)
   at Mono.Cecil.Cil.CodeReader.ReadScopes(Collection`1 scopes)
   at Mono.Cecil.Cil.CodeReader.ReadScope(ScopeDebugInformation scope)
   at Mono.Cecil.Cil.CodeReader.ReadDebugInfo()
   at Mono.Cecil.Cil.CodeReader.ReadMethodBody()
   at Mono.Cecil.Cil.CodeReader.ReadMethodBody(MethodDefinition method)
   at Mono.Cecil.MethodDefinition.<>c.<get_Body>b__41_0(MethodDefinition method, MetadataReader reader)
   at Mono.Cecil.ModuleDefinition.Read[TItem,TRet](TRet& variable, TItem item, Func`3 read)
   at Mono.Cecil.MethodDefinition.get_Body()
   at Mono.Cecil.MethodDefinition.get_DebugInformation()
   at Mono.Debugging.Soft.SoftDebuggerSession.LoadPdbType(TypeDefinition type, Dictionary`2 fileToSourceFileInfos) in E:\A\_work\84\s\external\debugger-libs\Mono.Debugging.Soft\SoftDebuggerSession.cs:line 2645
   at Mono.Debugging.Soft.SoftDebuggerSession.LoadPdbFile(String assemblyFileName, String pdbFileName) in E:\A\_work\84\s\external\debugger-libs\Mono.Debugging.Soft\SoftDebuggerSession.cs:line 2637
   at Mono.Debugging.Soft.SoftDebuggerSession.LoadDebugFile(String assemblyFileName, String debugFileName, Func`3 loadDebugFile) in E:\A\_work\84\s\external\debugger-libs\Mono.Debugging.Soft\SoftDebuggerSession.cs:line 2733
   at Mono.Debugging.Soft.SoftDebuggerSession.CheckBetterMatch(TypeMirror type, String file, Int32 line, Int32 column, Location found) in E:\A\_work\84\s\external\debugger-libs\Mono.Debugging.Soft\SoftDebuggerSession.cs:line 2755
   at Mono.Debugging.Soft.SoftDebuggerSession.FindLocationByMethod(MethodMirror method, String file, Int32 line, Int32 column, Boolean& insideTypeRange) in E:\A\_work\84\s\external\debugger-libs\Mono.Debugging.Soft\SoftDebuggerSession.cs:line 2942
   at Mono.Debugging.Soft.SoftDebuggerSession.FindLocationByType(TypeMirror type, String file, Int32 line, Int32 column, Boolean& genericMethod, Boolean& insideTypeRange) in E:\A\_work\84\s\external\debugger-libs\Mono.Debugging.Soft\SoftDebuggerSession.cs:line 2960
   at Mono.Debugging.Soft.SoftDebuggerSession.ResolveBreakpoints(TypeMirror type) in E:\A\_work\84\s\external\debugger-libs\Mono.Debugging.Soft\SoftDebuggerSession.cs:line 2454
   at Mono.Debugging.Soft.SoftDebuggerSession.HandleTypeLoadEvents(TypeLoadEvent[] events) in E:\A\_work\84\s\external\debugger-libs\Mono.Debugging.Soft\SoftDebuggerSession.cs:line 2008
   at Mono.Debugging.Soft.SoftDebuggerSession.HandleEventSet(EventSet es) in E:\A\_work\84\s\external\debugger-libs\Mono.Debugging.Soft\SoftDebuggerSession.cs:line 1549
   at Mono.Debugging.Soft.SoftDebuggerSession.EventHandler() in E:\A\_work\84\s\external\debugger-libs\Mono.Debugging.Soft\SoftDebuggerSession.cs:line 1471
```

This happens when doing `DllImport` calls onto an armeabi-v7a .so file on Android on VS for Windows. Interestingly, VS for Mac does not present the same issue with the same code/.so.

```
Microsoft Visual Studio Community 2017 
Version 15.6.6
VisualStudio.15.Release/15.6.6+27428.2037
Microsoft .NET Framework
Version 4.7.02556

Xamarin   4.9.0.753 (f0f46392f)
Xamarin.Android SDK   8.2.0.16 (HEAD/a78295902)
```

**Comment by mfkl** [comment]
Removed some Fody plugin and the problem is gone. Closing.

**Comment by tuyen-vuduc** [comment]
@mfkl Which plugin did you removed?

I faced the same issue where PropertyChanged and Realms are both installed.
