### ISSUE TITLE
System.IO.FileNotFoundException on ModuleReference.Resolve()

### ISSUE THREAD

**Issue by lucaneg** [jbevain/cecil#509]
Trying to parse the .NET library called System.EnterpriseServices.dll using the MWE of Program.cs
(see attachment for both). Stack trace of the exception:
```
System.IO.FileNotFoundException: Could not find file 'System.EnterpriseServices.Wrapper.dll'.
   at System.IO.FileStream.OpenHandle(FileMode mode, FileShare share, FileOptions options)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options)
   at Mono.Cecil.ModuleDefinition.ReadModule(String fileName, ReaderParameters parameters)
   at Mono.Cecil.MetadataReader.ReadModules()
   at Mono.Cecil.ModuleDefinition.Read[TItem,TRet](TRet& variable, TItem item, Func`3 read)
   at Mono.Cecil.AssemblyDefinition.get_Modules()
   at Mono.Cecil.MetadataResolver.Resolve(TypeReference type)
   at Mono.Cecil.MetadataResolver.Resolve(MethodReference method)
   at ConsoleApp.Program.Main(String[] args) in ConsoleApp\ConsoleApp\Program.cs:line 36
```

If the missing dll (also in the attachment) gets added to the same folder of the original one, the exception become the following:
```
Unhandled Exception: System.IO.IOException: The process cannot access the file 'System.EnterpriseServices.Wrapper.dll' because it is being used by another process.
   at System.IO.FileStream.OpenHandle(FileMode mode, FileShare share, FileOptions options)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options)
   at Mono.Cecil.ModuleDefinition.ReadModule(String fileName, ReaderParameters parameters)
   at Mono.Cecil.MetadataReader.ReadModules()
   at Mono.Cecil.ModuleDefinition.Read[TItem,TRet](TRet& variable, TItem item, Func`3 read)
   at Mono.Cecil.AssemblyDefinition.get_Modules()
   at Mono.Cecil.MetadataResolver.Resolve(TypeReference type)
   at Mono.Cecil.MetadataResolver.Resolve(MethodReference method)
   at ConsoleApp.Program.Main(String[] args) in ConsoleApp\ConsoleApp\Program.cs:line 33
```

Files: [mwe.zip](https://github.com/jbevain/cecil/files/1932021/mwe.zip)

**Comment by SimonCropp** [comment]
try putting a using around your file stream

**Comment by lucaneg** [comment]
Adding the using would close the files before they are parsed, hence preventing the second foreach to be executed (causing an ObjectDisposedException)

**Comment by jbevain** [comment]
@lucaneg you're preventing Cecil to open a file handle on the module by doing:

```csharp
FileStream input = new FileStream(moduleFile, FileMode.Open);
```

Do this instead:

```csharp
FileStream input = new FileStream(moduleFile, FileMode.Open, FileAccess.Read, FileShare.Read);
```
