### ISSUE TITLE
Resolving field and method definitions in Cecil 0.10 not implemented/supported?

### ISSUE THREAD

**Issue by philiplaureano** [jbevain/cecil#531]
Hi JB,

I'm trying to port one of my libraries to use .NET Standard 2.0, but I keep running into this exception:

System.NotImplementedException : The method or operation is not implemented.
   at Mono.Cecil.DefaultReflectionImporter.ResolveMethodDefinition(MethodBase method)
   at Mono.Cecil.DefaultReflectionImporter.ImportMethod(MethodBase method, ImportGenericContext context, ImportGenericKind import_kind)
   at Mono.Cecil.DefaultReflectionImporter.ImportReference(MethodBase method, IGenericParameterProvider context)
   at Deflector.ModuleDefinitionExtensions.ImportMethod[T](ModuleDefinition module, String methodName) in E:\Dropbox\Development\Deflector.NET\Deflector\Deflector\ModuleDefinitionExtensions.cs:line 92
   at Deflector.MethodCallInterceptionEmitter.ImportReferences(ModuleDefinition module) in E:\Dropbox\Development\Deflector.NET\Deflector\Deflector\MethodCallInterceptionEmitter.cs:line 44
   at Deflector.MethodBodyRewriterExtensions.Rewrite(IMethodBodyRewriter rewriter, AssemblyDefinition assembly, Func`2 methodFilter) in E:\Dropbox\Development\Deflector.NET\Deflector\Deflector\MethodBodyRewriterExtensions.cs:line 23
   at Deflector.MethodCallInterceptionExtensions.AddInterceptionHooks(AssemblyDefinition assemblyDefinition) in E:\Dropbox\Development\Deflector.NET\Deflector\Deflector\MethodCallInterceptionExtensions.cs:line 20
   at Deflector.Tests.MethodCallInterceptionTests.RewriteAssemblyOf[T]() in E:\Dropbox\Development\Deflector.NET\Deflector\Tests\MethodCallInterceptionTests.cs:line 17
   at Deflector.Tests.MethodCallInterceptionTests.Should_intercept_constructor_call() in E:\Dropbox\Development\Deflector.NET\Deflector\Tests\MethodCallInterceptionTests.cs:line 40

Is there a workaround for this issue in Cecil 0.10?

You can reproduce the results by checking out this branch from my repo: https://github.com/philiplaureano/Deflector.NET/tree/dotnet-standard

**Comment by atykhyy** [comment]
Look at #505. Until 0.11 is out, you'll have to compile Cecil for netstandard2.0 and make it so that `NET_CORE` is not defined. The only place you need an `#if` targeting netstandard2.0 is to comment out `Mono.Cecil.Rocks.SecurityDeclarationRocks`.

**Comment by jbevain** [comment]
Thanks, that's fixed in master, I'll push a 0.11 with a fix in the coming days.
