### ISSUE TITLE
NetStandard2.0 release?

### ISSUE THREAD

**Issue by eiriktsarpalis** [jbevain/cecil#599]
I'm getting the following exception when using the latest release (0.10.4) on netcoreapp2.2:
```
System.NotImplementedException: The method or operation is not implemented.
   at Mono.Cecil.DefaultReflectionImporter.ResolveFieldDefinition(FieldInfo field)
   at Mono.Cecil.DefaultReflectionImporter.ImportField(FieldInfo field, ImportGenericContext context)
   at Mono.Cecil.DefaultReflectionImporter.ImportReference(FieldInfo field, IGenericParameterProvider context)
   at Mono.Cecil.ModuleDefinition.ImportReference(FieldInfo field, IGenericParameterProvider context)
```
This seems to have been addressed in commit bde4fd363d3a8ac0c3f2514689f51ebf1160dd22 and I have verified that the error goes away when building off master.

Do you have plans on releasing a netstandard2.0 build of cecil?

**Comment by SimonCropp** [comment]
What nuget version are u using? That change should be in the current version

**Comment by jbevain** [comment]
I pushed 0.11 to nuget today with .NET Standard 2.0 support. Thanks!

**Comment by eiriktsarpalis** [comment]
Thank you!
