### ISSUE TITLE
Index was outside the bounds of the array in typeDefinition.Methods

### ISSUE THREAD

**Issue by nefcanto** [jbevain/cecil#607]
I'm using this line of code to access `MethodDefinition` collection of a given type.

	if (typeDefinitionInstance.HasMethods) 
	{
		var methodDefinitions = typeDefinitionInstance.Methods;
	}

But for some DLL files I get this error:

        Index was outside the bounds of the array.

	at Mono.Cecil.SignatureReader.GetPrimitiveType(ElementType etype)
	at Mono.Cecil.SignatureReader.ReadMethodSignature(IMethodSignature method)
	at Mono.Cecil.MetadataReader.ReadMethod(UInt32 method_rid, Collection`1 methods)
	at Mono.Cecil.MetadataReader.ReadMethods(TypeDefinition type)
	at Mono.Cecil.ModuleDefinition.Read[TItem,TRet](TRet& variable, TItem item, Func`3 read)
	at Mono.Cecil.TypeDefinition.get_Methods()

I don't have any other information here to help me troubleshoot what the problem might be. Could you please help?

**Comment by jbevain** [comment]
You need to upload a dll that reproduces the exception.

**Comment by jbevain** [comment]
Closing this. Feel free to re-open with an assembly that reproduces the crash. Thanks!
