### ISSUE TITLE
error MSB4018: System.InvalidCastException: Unable to cast object of type 'System.Byte' to type 'System.String'

### ISSUE THREAD

**Issue by pfdsilva** [jbevain/cecil#614]
Overview

> error MSB4018: System.InvalidCastException:Unable to cast object of type 'System.Byte' to type 'System.String'

 error occurs when I try to compile a project, xamarin.android, with linker option "SDK assemblies only" in **release mode ONLY**. 

To reproduce the error, create a xamarin.android project and add a reference to Oracle.ManagedDataAccess.Core (Version 2.18.6) nuget package. Then compile the project. If the Oracle.ManagedDataAccess.Core reference is removed, then the issue is NOT reproducible.
 
On compiling the project, I get the error with the following stack trace:

````The "LinkAssemblies" task failed unexpectedly.
System.InvalidCastException: Unable to cast object of type 'System.Byte' to type 'System.String'.
   at Mono.Cecil.MetadataBuilder.GetConstantSignature(ElementType type, Object value)
   at Mono.Cecil.MetadataBuilder.AddConstant(IConstantProvider owner, TypeReference type)
   at Mono.Cecil.MetadataBuilder.AddField(FieldDefinition field)
   at Mono.Cecil.MetadataBuilder.AddFields(TypeDefinition type)
   at Mono.Cecil.MetadataBuilder.AddType(TypeDefinition type)
   at Mono.Cecil.MetadataBuilder.AddTypes()
   at Mono.Cecil.MetadataBuilder.BuildTypes()
   at Mono.Cecil.MetadataBuilder.BuildModule()
   at Mono.Cecil.MetadataBuilder.BuildMetadata()
   at Mono.Cecil.ModuleWriter.<>c.<BuildMetadata>b__2_0(MetadataBuilder builder, MetadataReader _)
   at Mono.Cecil.ModuleDefinition.Read[TItem,TRet](TItem item, Func`3 read)
   at Mono.Cecil.ModuleWriter.BuildMetadata(ModuleDefinition module, MetadataBuilder metadata)
   at Mono.Cecil.ModuleWriter.Write(ModuleDefinition module, Disposable`1 stream, WriterParameters parameters)
   at Mono.Cecil.ModuleWriter.WriteModule(ModuleDefinition module, Disposable`1 stream, WriterParameters parameters)
   at Mono.Cecil.ModuleDefinition.Write(String fileName, WriterParameters parameters)
   at Mono.Cecil.AssemblyDefinition.Write(String fileName, WriterParameters parameters)
   at Mono.Linker.Steps.OutputStep.WriteAssembly(AssemblyDefinition assembly, String directory, WriterParameters writerParameters)
   at Mono.Linker.Steps.OutputStep.OutputAssembly(AssemblyDefinition assembly)
   at Mono.Linker.Steps.OutputStep.ProcessAssembly(AssemblyDefinition assembly)
   at Mono.Linker.Steps.BaseStep.Process(LinkContext context)
   at Mono.Linker.Pipeline.Process(LinkContext context)
   at MonoDroid.Tuner.Linker.Process(LinkerOptions options, ILogger logger, LinkContext& context)
   at Xamarin.Android.Tasks.LinkAssemblies.Execute(DirectoryAssemblyResolver res)
   at Xamarin.Android.Tasks.LinkAssemblies.Execute()
   at Microsoft.Build.BackEnd.TaskExecutionHost.Microsoft.Build.BackEnd.ITaskExecutionHost.Execute()
   at Microsoft.Build.BackEnd.TaskBuilder.<ExecuteInstantiatedTask>d__26.MoveNext()	App2.Android		````	

I think the code from where the exception is thrown is [here.](https://github.com/jbevain/cecil/blob/master/Mono.Cecil/AssemblyWriter.cs#L2185)

The issue is only noticed when using Xamarin.Android project and NOT reproduced with a simple .Net Core project.

**Comment by pfdsilva** [comment]
Hi @jbevain

Just out of curiosity, why is the issue only reproducible when I build the Xamarin.Android project in Release mode? If I build the project in debug mode, then the issue is not reproducible.

**Comment by jbevain** [comment]
@pfdsilva that's because in Debug mode Xamarin is not running assemblies through the linker.
