### ISSUE TITLE
Locally scoped constant arrays throw NotImplementedException in SignatureReader.ReadPrimitiveValue

### ISSUE THREAD

**Issue by ins0mniaque** [jbevain/cecil#642]
Using Fody on any assembly which contains a locally scoped constant array (of any type),

e.g.
```
public class TestClass
{
    public void TestMethod()
    {
        const int [ ] LocallyScopedConstArray = null;
    }
}
```

results in a NotImplementedException in SignatureReader.ReadPrimitiveValue.

```
System.NotImplementedException: Array

StackTrace:
   at Mono.Cecil.SignatureReader.ReadPrimitiveValue(ElementType type) in C:\Code\Fody\cecil\Mono.Cecil\AssemblyReader.cs:line 3635
   at Mono.Cecil.MetadataReader.ReadLocalConstant(UInt32 rid) in C:\Code\Fody\cecil\Mono.Cecil\AssemblyReader.cs:line 3017
   at Mono.Cecil.MetadataReader.ReadLocalScope(Row`6 record) in C:\Code\Fody\cecil\Mono.Cecil\AssemblyReader.cs:line 2974
   at Mono.Cecil.MetadataReader.ReadScope(MethodDefinition method) in C:\Code\Fody\cecil\Mono.Cecil\AssemblyReader.cs:line 2917
   at Mono.Cecil.Cil.PortablePdbReader.Read(MethodDefinition method) in C:\Code\Fody\cecil\Mono.Cecil.Cil\PortablePdb.cs:line 119
   at Mono.Cecil.ImmediateModuleReader.ReadMethodsSymbols(TypeDefinition type, ISymbolReader symbol_reader) in C:\Code\Fody\cecil\Mono.Cecil\AssemblyReader.cs:line 423
   at Mono.Cecil.ImmediateModuleReader.ReadTypesSymbols(Collection`1 types, ISymbolReader symbol_reader) in C:\Code\Fody\cecil\Mono.Cecil\AssemblyReader.cs:line 412
   at Mono.Cecil.ImmediateModuleReader.ReadSymbols(ModuleDefinition module) in C:\Code\Fody\cecil\Mono.Cecil\AssemblyReader.cs:line 401
   at Mono.Cecil.ModuleWriter.Write(ModuleDefinition module, Disposable`1 stream, WriterParameters parameters) in C:\Code\Fody\cecil\Mono.Cecil\AssemblyWriter.cs:line 89
   at Mono.Cecil.ModuleWriter.WriteModule(ModuleDefinition module, Disposable`1 stream, WriterParameters parameters) in C:\Code\Fody\cecil\Mono.Cecil\AssemblyWriter.cs:line 78
   at Mono.Cecil.ModuleDefinition.Write(String fileName, WriterParameters parameters) in C:\Code\Fody\cecil\Mono.Cecil\ModuleDefinition.cs:line 1136
   at InnerWeaver.WriteModule() in C:\projects\fody\FodyIsolated\ModuleWriter.cs:line 19
   at InnerWeaver.Execute() in C:\projects\fody\FodyIsolated\InnerWeaver.cs:line 114
```

**Comment by jbevain** [comment]
Thanks for reporting this!
