### ISSUE TITLE
Crash reading fields of type with local method and dynamic local

### ISSUE THREAD

**Issue by mrvoorhe** [jbevain/cecil#653]
If you have a `dynamic` local inside a local method, cecil crashes reading the fields of the compiler generated type.

Expected output of repro project
```
F:/Unity/dev/TestGround/DyanmicAndLocalMethodRepro/DyanmicAndLocalMethodRepro/bin/Debug/DyanmicAndLocalMethodRepro.exe
DyanmicAndLocalMethodRepro.Program/DynamicInNormalMethod
DyanmicAndLocalMethodRepro.Program/DynamicInNormalMethod/<>o__1`2
System.Runtime.CompilerServices.CallSite`1<System.Func`4<System.Runtime.CompilerServices.CallSite,System.Object,System.Object,System.Object>> DyanmicAndLocalMethodRepro.Program/DynamicInNormalMethod/<>o__1`2::<>p__0
System.Runtime.CompilerServices.CallSite`1<System.Func`3<System.Runtime.CompilerServices.CallSite,System.Object,System.Boolean>> DyanmicAndLocalMethodRepro.Program/DynamicInNormalMethod/<>o__1`2::<>p__1
System.Runtime.CompilerServices.CallSite`1<System.Func`3<System.Runtime.CompilerServices.CallSite,System.Object,T2>> DyanmicAndLocalMethodRepro.Program/DynamicInNormalMethod/<>o__1`2::<>p__2
DyanmicAndLocalMethodRepro.Program/NoDynamicLocalMethod
DyanmicAndLocalMethodRepro.Program/DynamicInsideLocalMethod
DyanmicAndLocalMethodRepro.Program/DynamicInsideLocalMethod/<>o__0

Unhandled Exception: System.NullReferenceException: Object reference not set to an instance of an object.
   at Mono.Cecil.SignatureReader.GetGenericParameter(GenericParameterType type, UInt32 var)
   at Mono.Cecil.SignatureReader.ReadTypeSignature(ElementType etype)
   at Mono.Cecil.SignatureReader.ReadGenericInstanceSignature(IGenericParameterProvider provider, IGenericInstance instance, UInt32 arity)
   at Mono.Cecil.SignatureReader.ReadTypeSignature(ElementType etype)
   at Mono.Cecil.SignatureReader.ReadGenericInstanceSignature(IGenericParameterProvider provider, IGenericInstance instance, UInt32 arity)
   at Mono.Cecil.SignatureReader.ReadTypeSignature(ElementType etype)
   at Mono.Cecil.MetadataReader.ReadFieldType(UInt32 signature)
   at Mono.Cecil.MetadataReader.ReadField(UInt32 field_rid, Collection`1 fields)
   at Mono.Cecil.MetadataReader.ReadFields(TypeDefinition type)
   at Mono.Cecil.TypeDefinition.<>c.<get_Fields>b__47_0(TypeDefinition type, MetadataReader reader)
   at Mono.Cecil.ModuleDefinition.Read[TItem,TRet](TRet& variable, TItem item, Func`3 read)
   at Mono.Cecil.TypeDefinition.get_Fields()
   at DyanmicAndLocalMethodRepro.Program.IterateAllFields(TypeDefinition type) in F:\Unity\dev\TestGround\DyanmicAndLocalMethodRepro\DyanmicAndLocalMethodRepro\Program.cs:line 30
   at DyanmicAndLocalMethodRepro.Program.IterateAllFields(TypeDefinition type) in F:\Unity\dev\TestGround\DyanmicAndLocalMethodRepro\DyanmicAndLocalMethodRepro\Program.cs:line 33
   at DyanmicAndLocalMethodRepro.Program.Main(String[] args) in F:\Unity\dev\TestGround\DyanmicAndLocalMethodRepro\DyanmicAndLocalMethodRepro\Program.cs:line 23
```

[DyanmicAndLocalMethodRepro.zip](https://github.com/jbevain/cecil/files/4252039/DyanmicAndLocalMethodRepro.zip)

**Comment by jbevain** [comment]
Why are you doing this to me Mike?

**Comment by jbevain** [comment]
OK I'll go on a limb, but I'm going to declare that's a C# compiler bug.

**Comment by jbevain** [comment]
Here's the Roslyn bug:

https://github.com/dotnet/roslyn/issues/41947

**Comment by mrvoorhe** [comment]
Thanks!

**Comment by jbevain** [comment]
Closing this then.
