### ISSUE TITLE
"Specified method is not supported" on net5.0

### ISSUE THREAD

**Issue by aalmada** [jbevain/cecil#669]
I'm using `ILRepack.MSBuild.Task 2.0.1` on `.NET 5.0.100-preview.4` with target framework `netstandard2.0`. 

I'm getting the following error when I run `dotnet build` on the command line:

```
C:\Projects\NetFabric.Hyperlinq\NetFabric.Hyperlinq.SourceGenerator\NetFabric.Hyperlinq.SourceGenerator.csproj(31,5): error : Specified method is not supported.
C:\Projects\NetFabric.Hyperlinq\NetFabric.Hyperlinq.SourceGenerator\NetFabric.Hyperlinq.SourceGenerator.csproj(31,5): error :    at Mono.Cecil.ModuleParameters.GetCurrentRuntime()
C:\Projects\NetFabric.Hyperlinq\NetFabric.Hyperlinq.SourceGenerator\NetFabric.Hyperlinq.SourceGenerator.csproj(31,5): error :    at Mono.Cecil.ModuleParameters..ctor()
C:\Projects\NetFabric.Hyperlinq\NetFabric.Hyperlinq.SourceGenerator\NetFabric.Hyperlinq.SourceGenerator.csproj(31,5): error :    at ILRepacking.ILRepack.Repack()
C:\Projects\NetFabric.Hyperlinq\NetFabric.Hyperlinq.SourceGenerator\NetFabric.Hyperlinq.SourceGenerator.csproj(31,5): error :    at ILRepack.MSBuild.Task.ILRepack.Execute()
```

I don't get the error when I build inside Visual Studio.

I don't know if it's a Cecil or ILRepack problem.

**Comment by jbevain** [comment]
Looks like a Cecil issue. Maybe .NET 5 updated the metadata runtime version and we're not handling that properly.

**Comment by jbevain** [comment]
That's an issue in ILRepack's Cecil. Cecil today doesn't throw a NotSupportedException in `GetCurrentRuntime`.
