### ISSUE TITLE
Cannot add a custom field to existing type on .NET Core

### ISSUE THREAD

**Issue by Serg046** [jbevain/cecil#692]
Say, I have some two classes SomeType and Test. Now I am about to read their assembly and add a property of Test type to SomeType:

```csharp
using System;
using System.IO;
using System.Reflection;
using Mono.Cecil;
using Mono.Cecil.Cil;
using FieldAttributes = Mono.Cecil.FieldAttributes;
using MethodAttributes = Mono.Cecil.MethodAttributes;
using TypeAttributes = Mono.Cecil.TypeAttributes;

namespace CoreCecil
{
	class Program
	{
		static void Main(string[] args)
		{
			//var asmDef = CreateAsm();
			var asmDef = AssemblyDefinition.ReadAssembly(typeof(SomeType).Module.FullyQualifiedName);

			var typeDef = asmDef.MainModule.GetType(typeof(SomeType).FullName);
			typeDef.Fields.Add(new FieldDefinition("IntField", FieldAttributes.Public,
				asmDef.MainModule.ImportReference(typeof(int))));
			typeDef.Fields.Add(new FieldDefinition("TestField", FieldAttributes.Public,
				asmDef.MainModule.ImportReference(typeof(Test))));

			var mem = new MemoryStream();
			asmDef.Write(mem);
			var asm = Assembly.Load(mem.ToArray());
			var type = asm.GetType(typeof(SomeType).FullName);
			dynamic instance = Activator.CreateInstance(type);

			instance.IntField = 5;
			instance.TestField = new Test {X = 7}; // Fails for read assemblies on .NET Core
		}

		private static AssemblyDefinition CreateAsm()
		{
			var asmDef = AssemblyDefinition.CreateAssembly(
				new AssemblyNameDefinition("TestAsm", new Version(0, 1)), "TestModule", ModuleKind.Dll);
			var typeDef = new TypeDefinition("CoreCecil", "SomeType", TypeAttributes.Class | TypeAttributes.Public,
				asmDef.MainModule.ImportReference(typeof(object)));
			typeDef.Methods.Add(GenerateCtor(asmDef));
			
			asmDef.MainModule.Types.Add(typeDef);
			return asmDef;
		}

		private static MethodDefinition GenerateCtor(AssemblyDefinition asmDef)
		{
			var ctor = new MethodDefinition(".ctor",
				MethodAttributes.Public | MethodAttributes.HideBySig
				                        | MethodAttributes.SpecialName | MethodAttributes.RTSpecialName
				, asmDef.MainModule.ImportReference(typeof(void)));
			ctor.Body.Instructions.Add(Instruction.Create(OpCodes.Ret));
			return ctor;
		}
	}

	public class SomeType
	{

	}

	public class Test
	{
		public int X { get; set; }

		public void Print() => Console.WriteLine(X);
	}
}
```
The example fails on the last line of Main. But the interesting thing is that it doesn't fail if you create a new assembly. Another interesting thing - both the cases work on full .NET Framework. You can run the example there and see an exception - https://dotnetfiddle.net/9T7lEF

**Comment by Serg046** [comment]
Tried to add a method - the same result. I can add it to a new assembly but can't to existing one.
The lib cannot convert the type although I import `Test` using `Module.ImportReference(...)`

```csharp
var methodInfo = typeof(Console).GetMethods()
	.Single(m => m.Name == nameof(Console.WriteLine)
	             && m.GetParameters().Length == 1
	             && m.GetParameters()[0].ParameterType == typeof(object));

var methodDef = new MethodDefinition("Print", MethodAttributes.Public,
	asmDef.MainModule.ImportReference(typeof(void)));
methodDef.Parameters.Add(new ParameterDefinition(asmDef.MainModule.ImportReference(typeof(Test))));
methodDef.Body.Instructions.Add(Instruction.Create(OpCodes.Ldarg_1));
methodDef.Body.Instructions.Add(Instruction.Create(OpCodes.Call,
	asmDef.MainModule.ImportReference(methodInfo)));
methodDef.Body.Instructions.Add(Instruction.Create(OpCodes.Ret));
typeDef.Methods.Add(methodDef);
```

**Comment by ltrzesniewski** [comment]
Let me guess: are you running the Cecil code from .NET Framework? You shouldn't use `ImportReference(Type)`, as this will literally import the `Type` currently used by the code, for instance `typeof(int)` will mean `System.Int32` from `mscorlib`, which is *not* what you want on .NET Core.

Use `ImportReference(TypeReference)` instead, and use `MainModule.TypeSystem` to get access to the standard types.

**Comment by Serg046** [comment]
>Let me guess: are you running the Cecil code from .NET Framework?

No, you can check https://dotnetfiddle.net/9T7lEF and see it is .NET Core 3.1

> to get access to the standard types

Standard types work fine in the example that's why I added that Int32 field. I guess even other external types work fine.
The issue is the fields of some type from the same assembly like `Test TestField`. I even added a comment
`instance.TestField = new Test {X = 7}; // Fails for read assemblies on .NET Core`

**Comment by SimonCropp** [comment]
@Serg046 in that dotnetfiddle, it seems you are creating and loading a new assembly that conflicts with the currently loaded assembly. ie the Test class will exists in the current appdomain from the original assembly, and then again from the newly created assembly.

**Comment by SimonCropp** [comment]
if it works on netframework, i would argue that it should not

**Comment by Serg046** [comment]
It shouldn't conflict imo as I import explicitly using `ImportReference`. Anyway, different dlls should be able to contain the types with the same name, namespace and structure. But yes, they should be different so there is no a possibility to cast one to another.

As far as I remember Cecil on .NET Core doesn't understand that the type is imported. I remember that when I tried to print FullyQualifiedName of type, I got something like "c://tests/project/lib.dll" for netframework but "<module>" for netcore. I will try to analyze it again.

**Comment by Serg046** [comment]
Yes, I think this is the root cause:

```csharp
var asmDef = AssemblyDefinition.ReadAssembly(typeof(SomeType).Module.FullyQualifiedName);

var typeDef = asmDef.MainModule.GetType(typeof(SomeType).FullName);
var fieldDef = new FieldDefinition("TestField", FieldAttributes.Public, asmDef.MainModule.ImportReference(typeof(Test)));
typeDef.Fields.Add(fieldDef);

var mem = new MemoryStream();
asmDef.Write(mem);
var asm = Assembly.Load(mem.ToArray());
var type = asm.GetType(typeof(SomeType).FullName);
var field = type.GetField("TestField");

Console.WriteLine(fieldDef.FieldType.Module.FullyQualifiedName);
Console.WriteLine(field.FieldType.Module.FullyQualifiedName);
```

```
/app/j4pviu0d.exe
<Unknown>
```
https://dotnetfiddle.net/On1bHl

So Cecil re-writes the field type and uses internal type instead of the type from "/app/j4pviu0d.exe" for some reason. But if you run it on full framework, you will see the same output. Imo .NET Core behaviour looks like a bug.

**Comment by Serg046** [comment]
It seems like

```csharp
var existingFile = typeof(SomeType).Module.FullyQualifiedName;
var newFile = existingFile.Replace(".exe", "_000002.exe");
File.Copy(existingFile, newFile);
var asmDef = AssemblyDefinition.ReadAssembly(newFile);
var programTypeDef = asmDef.MainModule.GetType(typeof(Program).FullName);
var testTypeDef = asmDef.MainModule.GetType(typeof(Test).FullName);
asmDef.MainModule.Types.Remove(programTypeDef);
asmDef.MainModule.Types.Remove(testTypeDef);
asmDef.Name.Version = new Version(2, 0);

var typeDef = asmDef.MainModule.GetType(typeof(SomeType).FullName);
var fieldDef = new FieldDefinition("TestField", FieldAttributes.Public, asmDef.MainModule.ImportReference(typeof(Test)));
typeDef.Fields.Add(fieldDef);

var mem = new MemoryStream();
asmDef.Write(mem);
var asm = Assembly.Load(mem.ToArray());
var type = asm.GetType(typeof(SomeType).FullName);
var field = type.GetField("TestField");

Console.WriteLine(fieldDef.FieldType.Module.FullyQualifiedName);
Console.WriteLine(field.FieldType.Module.FullyQualifiedName);
```
```
/app/ypp1u3ga_000002.exe
Unhandled exception. System.TypeLoadException: Could not load type 'CoreCecil.Test' from assembly 'ypp1u3ga.exe, Version=2.0.0.0, Culture=neutral, PublicKeyToken=null'.
   at System.Signature.GetSignature(Void* pCorSig, Int32 cCorSig, RuntimeFieldHandleInternal fieldHandle, IRuntimeMethodInfo methodHandle, RuntimeType declaringType)
   at System.Reflection.RtFieldInfo.InitializeFieldType()
   at CoreCecil.Program.Main(String[] args)
```
https://dotnetfiddle.net/vwfDmN

I guess it tries to understand that the type could be re-used based on some token as I even tried to copy the file and change the version. But it still tries to load the type from its own assembly...

**Comment by Serg046** [comment]
The fix is easy. You just need to rename Ceciled assembly so that the names are not conflicted on .NET core. So the following code works fine:

```
var asmDef = AssemblyDefinition.ReadAssembly(typeof(SomeType).Module.FullyQualifiedName);

//--------------------------------------------------------------------------------------------------------
asmDef.Name.Name += "Fake"; // Added this line ---------------------------------------------------
//--------------------------------------------------------------------------------------------------------

var typeDef = asmDef.MainModule.GetType(typeof(SomeType).FullName);
var fieldDef = new FieldDefinition("TestField", FieldAttributes.Public, asmDef.MainModule.ImportReference(typeof(Test)));
typeDef.Fields.Add(fieldDef);

var mem = new MemoryStream();
asmDef.Write(mem);
var asm = Assembly.Load(mem.ToArray());
var type = asm.GetType(typeof(SomeType).FullName);
var field = type.GetField("TestField");

Console.WriteLine(fieldDef.FieldType.Module.FullyQualifiedName);
Console.WriteLine(field.FieldType.Module.FullyQualifiedName);
```
https://dotnetfiddle.net/iZpEwC
