### ISSUE TITLE
ReadPrimitiveValue throws System.NotImplementedException: GenericInst

### ISSUE THREAD

**Issue by marek-safar** [jbevain/cecil#712]
Extracted from https://github.com/mono/linker/issues/1717. It seems like another cases of #644 which needs fixing

```c#
Unhandled exception. System.NotImplementedException: GenericInst
   at Mono.Cecil.SignatureReader.ReadPrimitiveValue(ElementType type)
   at Mono.Cecil.SignatureReader.ReadConstantSignature(ElementType type)
   at Mono.Cecil.MetadataReader.ReadLocalConstant(UInt32 rid)
   at Mono.Cecil.MetadataReader.ReadLocalScope(Row`6 record)
   at Mono.Cecil.MetadataReader.ReadScope(MethodDefinition method)
   at Mono.Cecil.Cil.PortablePdbReader.ReadScope(MethodDebugInformation method_info)
   at Mono.Cecil.Cil.PortablePdbReader.Read(MethodDefinition method)
   at Mono.Cecil.Cil.CodeReader.ReadMethodBody()
   at Mono.Cecil.Cil.CodeReader.ReadMethodBody(MethodDefinition method)
   at Mono.Cecil.MetadataReader.ReadMethodBody(MethodDefinition method)
   at Mono.Cecil.MethodDefinition.<>c.<get_Body>b__41_0(MethodDefinition method, MetadataReader reader)
   at Mono.Cecil.ModuleDefinition.Read[TItem,TRet](TRet& variable, TItem item, Func`3 read)
   at Mono.Cecil.MethodDefinition.get_Body()
```

**Comment by jbevain** [comment]
Thanks for filing this, I'll have a look.

**Comment by marek-safar** [comment]
@jbevain any update on this issue?

**Comment by jbevain** [comment]
@marek-safar sorry that fell through the cracks. Looking at this.
